<?php
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_colaboratorios_espacios',
        'title' => 'Colaboratorios - Espacios Section',
                'show_in_rest' => true,
        'fields' => array(
            array(
                'key' => 'field_espacios_header',
                'label' => 'Encabezado',
                'name' => 'header',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_espacios_badge',
                        'label' => 'Badge',
                        'name' => 'badge',
                        'type' => 'text',
                        'default_value' => 'Espacios y Equipamiento',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_espacios_badge_color',
                        'label' => 'Color del Badge',
                        'name' => 'badge_color',
                        'type' => 'color_picker',
                        'default_value' => '#40E0D0',
                    ),
                    array(
                        'key' => 'field_espacios_title',
                        'label' => 'Título',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Infraestructura Física',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_espacios_description',
                        'label' => 'Descripción',
                        'name' => 'description',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 1,
                        'button_label' => 'Agregar Párrafo',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_espacios_description_paragraph',
                                'label' => 'Párrafo',
                                'name' => 'paragraph',
                                'type' => 'textarea',
                                'rows' => 4,
                                'new_lines' => 'br',
                                'required' => 1,
                            ),
                        ),
                        'default_value' => array(
                            array(
                                'paragraph' => 'Los Colaboratorios han sido diseñados como espacios versátiles y funcionales que facilitan diferentes tipos de actividades y procesos de producción digital. Los estudios de grabación están equipados con sistemas de iluminación profesional, tratamiento acústico y equipos de captura de audio y video de alta calidad. Estos espacios permiten la producción de contenidos audiovisuales con estándares profesionales, desde entrevistas y documentales hasta contenidos educativos y piezas de comunicación.',
                            ),
                            array(
                                'paragraph' => 'Las salas de edición proporcionan ambientes optimizados para el trabajo de post-producción, con estaciones de trabajo equipadas con software especializado y monitores calibrados. Los espacios de co-creación son áreas flexibles que pueden adaptarse a diferentes necesidades, desde sesiones de trabajo colaborativo hasta presentaciones y exhibiciones. Las áreas de proyección facilitan la visualización de contenidos y la realización de eventos comunitarios, mientras que las zonas de trabajo colaborativo fomentan la interacción y el intercambio de ideas entre participantes.',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_espacios_image',
                        'label' => 'Imagen Principal',
                        'name' => 'image',
                        'type' => 'image',
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'instructions' => 'Imagen en formato 16:9 (aspect-video)',
                        'required' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_espacios_spaces',
                'label' => 'Nuestros Espacios',
                'name' => 'spaces',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_spaces_title',
                        'label' => 'Título de la Sección',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Nuestros Espacios',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_spaces_items',
                        'label' => 'Espacios',
                        'name' => 'items',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 4,
                        'max' => 4,
                        'button_label' => 'Agregar Espacio',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_space_icon',
                                'label' => 'Icono',
                                'name' => 'icon',
                                'type' => 'select',
                                'choices' => array(
                                    'video' => 'Video',
                                    'monitor' => 'Monitor',
                                    'users' => 'Users',
                                    'presentation' => 'Presentation',
                                ),
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_space_title',
                                'label' => 'Título',
                                'name' => 'title',
                                'type' => 'text',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_space_description',
                                'label' => 'Descripción',
                                'name' => 'description',
                                'type' => 'text',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_space_link',
                                'label' => 'Enlace',
                                'name' => 'link',
                                'type' => 'url',
                                'default_value' => '#',
                            ),
                        ),
                        'default_value' => array(
                            array(
                                'icon' => 'video',
                                'title' => 'Estudios de Grabación',
                                'description' => 'Equipados con sistemas de iluminación profesional y tratamiento acústico.',
                                'link' => '#',
                            ),
                            array(
                                'icon' => 'monitor',
                                'title' => 'Salas de Edición',
                                'description' => 'Ambientes optimizados con software especializado y monitores calibrados.',
                                'link' => '#',
                            ),
                            array(
                                'icon' => 'users',
                                'title' => 'Espacios de Co-creación',
                                'description' => 'Áreas flexibles adaptables a diferentes necesidades colaborativas.',
                                'link' => '#',
                            ),
                            array(
                                'icon' => 'presentation',
                                'title' => 'Áreas de Proyección',
                                'description' => 'Espacios para visualización de contenidos y eventos comunitarios.',
                                'link' => '#',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_espacios_equipment',
                'label' => 'Equipamiento Tecnológico',
                'name' => 'equipment',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_equipment_title',
                        'label' => 'Título',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Equipamiento Tecnológico',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_equipment_description',
                        'label' => 'Descripción',
                        'name' => 'description',
                        'type' => 'textarea',
                        'rows' => 2,
                        'default_value' => 'El equipamiento tecnológico de los Colaboratorios ha sido cuidadosamente seleccionado para proporcionar herramientas profesionales que permitan la producción de contenidos de alta calidad.',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_equipment_items',
                        'label' => 'Items de Equipamiento',
                        'name' => 'items',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 3,
                        'max' => 3,
                        'button_label' => 'Agregar Item',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_equipment_item_image',
                                'label' => 'Imagen',
                                'name' => 'image',
                                'type' => 'image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'instructions' => 'Imagen en formato 2:1',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_equipment_item_title',
                                'label' => 'Título',
                                'name' => 'title',
                                'type' => 'text',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_equipment_item_description',
                                'label' => 'Descripción',
                                'name' => 'description',
                                'type' => 'textarea',
                                'rows' => 3,
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_equipment_item_cta',
                                'label' => 'Call to Action',
                                'name' => 'cta',
                                'type' => 'group',
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_equipment_item_cta_text',
                                        'label' => 'Texto',
                                        'name' => 'text',
                                        'type' => 'text',
                                        'required' => 1,
                                    ),
                                    array(
                                        'key' => 'field_equipment_item_cta_link',
                                        'label' => 'Enlace',
                                        'name' => 'link',
                                        'type' => 'url',
                                        'default_value' => '#',
                                        'required' => 1,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_equipment_item_layout',
                                'label' => 'Imagen a la Derecha',
                                'name' => 'image_right',
                                'type' => 'true_false',
                                'ui' => 1,
                                'default_value' => 0,
                                'instructions' => 'Activa para mostrar la imagen a la derecha del texto',
                            ),
                        ),
                        'default_value' => array(
                            array(
                                'title' => 'Equipo de Producción Audiovisual',
                                'description' => 'Los equipos de producción audiovisual incluyen cámaras de video profesionales, sistemas de estabilización, micrófonos especializados y accesorios que permiten diferentes tipos de producciones audiovisuales.',
                                'cta' => array(
                                    'text' => 'Ver equipamiento',
                                    'link' => '#',
                                ),
                                'image_right' => 0,
                            ),
                            array(
                                'title' => 'Estaciones de Edición Digital',
                                'description' => 'Las estaciones de edición digital están equipadas con computadoras de alto rendimiento, monitores profesionales y una suite completa de software para edición de video, audio, diseño gráfico y animación.',
                                'cta' => array(
                                    'text' => 'Ver estaciones',
                                    'link' => '#',
                                ),
                                'image_right' => 1,
                            ),
                            array(
                                'title' => 'Hardware Especializado',
                                'description' => 'El hardware especializado incluye tabletas gráficas, sistemas de captura de video, interfaces de audio y otros dispositivos que amplían las posibilidades creativas. Las licencias de software cubren todas las necesidades de producción digital.',
                                'cta' => array(
                                    'text' => 'Ver hardware',
                                    'link' => '#',
                                ),
                                'image_right' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_espacios_virtual_tour',
                'label' => 'Tour Virtual',
                'name' => 'virtual_tour',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_virtual_tour_title',
                        'label' => 'Título',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Tour Virtual 360°',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_virtual_tour_description',
                        'label' => 'Descripción',
                        'name' => 'description',
                        'type' => 'textarea',
                        'rows' => 3,
                        'default_value' => 'El recorrido virtual 360° ofrece una experiencia inmersiva que permite a los usuarios potenciales explorar las instalaciones y equipamiento de los Colaboratorios de manera interactiva.',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_virtual_tour_features',
                        'label' => 'Características',
                        'name' => 'features',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 1,
                        'button_label' => 'Agregar Característica',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_virtual_tour_feature_text',
                                'label' => 'Texto',
                                'name' => 'text',
                                'type' => 'text',
                                'required' => 1,
                            ),
                        ),
                        'default_value' => array(
                            array(
                                'text' => 'Videos explicativos del equipamiento',
                            ),
                            array(
                                'text' => 'Fichas técnicas detalladas',
                            ),
                            array(
                                'text' => 'Ejemplos de productos realizados',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_virtual_tour_button',
                        'label' => 'Botón',
                        'name' => 'button',
                        'type' => 'group',
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_virtual_tour_button_text',
                                'label' => 'Texto del Botón',
                                'name' => 'text',
                                'type' => 'text',
                                'default_value' => 'Iniciar Tour Virtual 360°',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_virtual_tour_button_action',
                                'label' => 'Acción del Botón',
                                'name' => 'action',
                                'type' => 'text',
                                'default_value' => 'loadTourVirtual()',
                                'instructions' => 'Nombre de la función JavaScript a ejecutar',
                                'required' => 1,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_virtual_tour_image',
                        'label' => 'Imagen',
                        'name' => 'image',
                        'type' => 'image',
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'instructions' => 'Imagen en formato 4:3 para el tour virtual',
                        'required' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_espacios_accessibility',
                'label' => 'Accesibilidad y Uso',
                'name' => 'accessibility',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_accessibility_title',
                        'label' => 'Título',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Accesibilidad y Uso',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_accessibility_description',
                        'label' => 'Descripción',
                        'name' => 'description',
                        'type' => 'textarea',
                        'rows' => 3,
                        'default_value' => 'Las políticas de uso de los Colaboratorios están diseñadas para maximizar el acceso comunitario mientras se garantiza la sostenibilidad y el buen uso de los recursos.',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_accessibility_features',
                        'label' => 'Características',
                        'name' => 'features',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 1,
                        'button_label' => 'Agregar Característica',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_accessibility_feature_text',
                                'label' => 'Texto',
                                'name' => 'text',
                                'type' => 'text',
                                'required' => 1,
                            ),
                        ),
                        'default_value' => array(
                            array(
                                'text' => 'Horarios flexibles para diferentes grupos',
                            ),
                            array(
                                'text' => 'Requisitos de acceso inclusivos',
                            ),
                            array(
                                'text' => 'Protocolos de seguridad establecidos',
                            ),
                            array(
                                'text' => 'Sistema de registro y seguimiento',
                            ),
                            array(
                                'text' => 'Manejo de emergencias y situaciones imprevistas',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_accessibility_button',
                        'label' => 'Botón',
                        'name' => 'button',
                        'type' => 'group',
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_accessibility_button_text',
                                'label' => 'Texto del Botón',
                                'name' => 'text',
                                'type' => 'text',
                                'default_value' => 'Ver políticas completas',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_accessibility_button_link',
                                'label' => 'Enlace del Botón',
                                'name' => 'link',
                                'type' => 'url',
                                'default_value' => '#',
                                'required' => 1,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_accessibility_image',
                        'label' => 'Imagen',
                        'name' => 'image',
                        'type' => 'image',
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'instructions' => 'Imagen para la sección de accesibilidad (formato 4:3 recomendado)',
                        'required' => 1,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/subpage-templates/colaboratorios/espacios.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => false,
    ));

endif;
