<?php
if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_colaboratorios_impacto',
        'title' => 'Colaboratorios - Impacto',
        'fields' => array(
            array(
                'key' => 'field_impacto_hero',
                'label' => 'Sección Hero',
                'name' => 'hero',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_impacto_hero_title',
                        'label' => 'Título',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Métricas de Impacto',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_impacto_hero_description',
                        'label' => 'Descripción',
                        'name' => 'description',
                        'type' => 'textarea',
                        'rows' => 3,
                        'default_value' => 'El dashboard interactivo de los Colaboratorios proporciona una visualización dinámica del impacto del programa a través de diferentes indicadores cuantitativos y cualitativos.',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_impacto_hero_button',
                        'label' => 'Botón',
                        'name' => 'button',
                        'type' => 'group',
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_impacto_hero_button_text',
                                'label' => 'Texto del Botón',
                                'name' => 'text',
                                'type' => 'text',
                                'default_value' => 'Explorar métricas',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_hero_button_target',
                                'label' => 'ID de Sección Objetivo',
                                'name' => 'target',
                                'type' => 'text',
                                'default_value' => 'metricas',
                                'instructions' => 'ID de la sección a la que apuntará el botón (sin el símbolo #)',
                                'required' => 1,
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_impacto_overview',
                'label' => 'Sección de Impacto',
                'name' => 'impact_overview',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_impacto_overview_title',
                        'label' => 'Título Principal',
                        'name' => 'title',
                        'type' => 'text',
                        'default_value' => 'Impacto y Alcance de los Colaboratorios',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_impacto_overview_subtitle',
                        'label' => 'Subtítulo',
                        'name' => 'subtitle',
                        'type' => 'text',
                        'default_value' => 'Descubre cómo los Colaboratorios están transformando comunidades a través de la innovación, el aprendizaje y la colaboración.',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_impacto_metrics_card',
                        'label' => 'Tarjeta de Métricas',
                        'name' => 'metrics_card',
                        'type' => 'group',
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_impacto_metrics_title',
                                'label' => 'Título',
                                'name' => 'title',
                                'type' => 'text',
                                'default_value' => 'Métricas de Impacto',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_metrics_description',
                                'label' => 'Descripción',
                                'name' => 'description',
                                'type' => 'textarea',
                                'rows' => 3,
                                'default_value' => 'Dashboard interactivo que visualiza indicadores cuantitativos y cualitativos, incluyendo beneficiarios por demografía, proyectos por categoría y horas de formación en múltiples modalidades.',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_metrics_badge',
                                'label' => 'Texto del Badge',
                                'name' => 'badge',
                                'type' => 'text',
                                'default_value' => 'Análisis de Impacto',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_metrics_badge_link',
                                'label' => 'Enlace del Badge',
                                'name' => 'badge_link',
                                'type' => 'url',
                                'default_value' => '#',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_metrics_image',
                                'label' => 'Imagen',
                                'name' => 'image',
                                'type' => 'image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'instructions' => 'Imagen para la tarjeta de métricas (formato 4:3 recomendado)',
                                'required' => 1,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_impacto_secondary_cards',
                        'label' => 'Tarjetas Secundarias',
                        'name' => 'secondary_cards',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 2,
                        'max' => 2,
                        'button_label' => 'Agregar Tarjeta',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_impacto_card_title',
                                'label' => 'Título',
                                'name' => 'title',
                                'type' => 'text',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_card_description',
                                'label' => 'Descripción',
                                'name' => 'description',
                                'type' => 'textarea',
                                'rows' => 3,
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_card_badge',
                                'label' => 'Texto del Badge',
                                'name' => 'badge',
                                'type' => 'text',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_card_badge_link',
                                'label' => 'Enlace del Badge',
                                'name' => 'badge_link',
                                'type' => 'url',
                                'default_value' => '#',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_impacto_card_image',
                                'label' => 'Imagen',
                                'name' => 'image',
                                'type' => 'image',
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'instructions' => 'Imagen para la tarjeta (formato 4:3 recomendado)',
                                'required' => 1,
                            ),
                        ),
                        'default_value' => array(
                            array(
                                'title' => 'Proyectos Destacados',
                                'description' => 'Galería de iniciativas exitosas que documentan objetivos, desarrollo y resultados alcanzados, con evaluación de impacto comunitario y testimonios de beneficiarios.',
                                'badge' => 'Casos de Éxito',
                            ),
                            array(
                                'title' => 'Alianzas y Colaboraciones',
                                'description' => 'Red de colaboración que integra instituciones educativas, organizaciones sociales, entidades gubernamentales y sector privado para potenciar el impacto del programa.',
                                'badge' => 'Ecosistema de Aliados',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_impacto_testimonials',
                        'label' => 'Sección de Testimonios',
                        'name' => 'testimonials',
                        'type' => 'group',
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_testimonials_title',
                                'label' => 'Título',
                                'name' => 'title',
                                'type' => 'text',
                                'default_value' => 'Historias de Transformación',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_testimonials_description',
                                'label' => 'Descripción',
                                'name' => 'description',
                                'type' => 'textarea',
                                'rows' => 3,
                                'default_value' => 'La documentación audiovisual de los procesos de cambio generados por los Colaboratorios constituye un valioso archivo de memoria y aprendizaje, capturando las voces y experiencias de participantes.',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_testimonials_items',
                                'label' => 'Testimonios',
                                'name' => 'items',
                                'type' => 'repeater',
                                'layout' => 'block',
                                'min' => 1,
                                'max' => 6,
                                'button_label' => 'Agregar Testimonio',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_testimonial_quote',
                                        'label' => 'Testimonio',
                                        'name' => 'quote',
                                        'type' => 'textarea',
                                        'rows' => 3,
                                        'required' => 1,
                                    ),
                                    array(
                                        'key' => 'field_testimonial_author',
                                        'label' => 'Autor',
                                        'name' => 'author',
                                        'type' => 'text',
                                        'required' => 1,
                                    ),
                                    array(
                                        'key' => 'field_testimonial_role',
                                        'label' => 'Rol',
                                        'name' => 'role',
                                        'type' => 'text',
                                        'required' => 1,
                                    ),
                                    array(
                                        'key' => 'field_testimonial_image',
                                        'label' => 'Foto',
                                        'name' => 'image',
                                        'type' => 'image',
                                        'return_format' => 'array',
                                        'preview_size' => 'thumbnail',
                                        'instructions' => 'Foto del autor (formato cuadrado recomendado)',
                                        'required' => 1,
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/subpage-templates/colaboratorios/impacto.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => false,
    ));

endif;
